### PR TITLE
handle empty arrays

### PR DESCRIPTION
**Pull request by alexgleith**
Overview image writing will fail if there is all nodata in a band. This fixes it.

### CODE REVIEW

**Comment by jeremyh** [comment]
Thanks Alex! It looks like it just needs a `black` format to pass the checks.

**Comment by jeremyh** [comment]
Install pre-commit to make it automatic: https://github.com/GeoscienceAustralia/eo-datasets#pre-commit-setup

**Comment by jeremyh** [comment]
... hm, I'm guessing you did, but a new version of Black changed the formatting slightly. We're pinned to `stable`, not a specific version, but it's not exactly stable yet....

**Comment by jeremyh** [comment]
Black issue addressed in #67

**Comment by jeremyh** [comment]
Now it's a test failure
```
>   # Check if there's a non-empty array first
>   if the_data:
E   ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by alexgleith** [comment]
I think the tests pass now @jeremyh :-)

**Review by jeremyh — APPROVED** [review]
:+1: Thanks Alex

**Pull request merged**
