### PR TITLE
Add a method to add a uuid directory to the output file structure.

### PR DESCRIPTION
**Pull request by dunkgray**
A change to eodatasets to get the uuid directory functionality.  This is confined to a method and the method will not be called in the eodatasets code.   I'm hoping this can be an interum soln to use until we get the full go-ahead.

### CODE REVIEW

**Comment by dunkgray** [comment]
hey Jeremy, I've finished adding more code.  Fell free to review now.

**Review by jeremyh — CHANGES_REQUESTED** [review]
Thanks Duncan! Nice work.

As discussed, we might change the public api to be consistent with the other public options. Rather than a separate function, it can be a new option for the `naming_conventions` parameter.

eg.
```python
 with DatasetAssembler(
            Path('/some/output/collection/path'), 
            naming_conventions='dea-uuid') as p:
    ...
```

And perhaps change the s2 test/s to use it? https://github.com/GeoscienceAustralia/eo-datasets/blob/eodatasets3/tests/integration/test_assemble.py#L243

**Comment by alexgleith** [comment]
Hey @dunkgray we walked this back, right? I guess we can leave in the UUID option, but we don't actually want to do it for Sentinel-2, was my understanding.

**Comment by dunkgray** [comment]
I've put in a new pull request

**Pull request closed without merging**
